name: My first pipeline

on:
    push: 
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clone the code
              uses: actions/checkout@v4
            - name: Build image
              run:
                docker build -t rufneemkams4/cicd-portfolio .
            - name: Docker login
              uses: docker/login-action@v3
              with:
                username: rufneemkams4
                password: ${{ secrets.DOCKER_PASS2 }}
            - name: Push image
              run:
                docker push rufneemkams4/cicd-portfolio

